server:
  port: 20185
  #servlet:
  #  path: /fight

# 日志配置文件路径
logging:
  config: classpath:logback-spring.xml
  
  #mybatis config
mybatis:
  mapper-locations:  classpath:/mybatis/*.xml
  executor-type: reuse
  type-aliases-package: com.wm.po
  configuration:
    map-underscore-to-camel-case: true

#datasource config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cms_2919?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    hikari.maximum-pool-size: 15
    hikari.max-lifetime: 1765000

  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    timeout: 1000
